sudo: false

language: node_js

node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm config set spin false

before_script:
  - npm i -g npm@4

install:
  - yarn

script:
  - yarn run build:ci

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH
