sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.11.2

services:
  - docker

script:
  - docker network create dsproxy_default
  - docker-compose -f docker-compose.yml -f docker-compose.test.ci.yml build
