version: '2.1'

services:
  ng2admin:
    image: digitalstate/portal:0.1.7
    environment:
      - VIRTUAL_HOST
      - DISCOVERY_HOST
    working_dir: /var/www

networks:
  default:
    external:
      name: '${NETWORK}'
