version: '2.1'

services:
  ng2admin:
    image: 'digitalstate/portal:${IMAGE_TAG}'
    environment:
      - VIRTUAL_HOST
      - DISCOVERY_HOST
    working_dir: /var/www

networks:
  default:
    external:
      name: '${NETWORK}'
