version: '2.1'

services:
    portal_ng2admin:
        build: .
        volumes:
            - '${DIRECTORY}/ng2-admin/src:/var/www/src'
        environment:
            - VIRTUAL_HOST
        working_dir: /var/www
        command: bash -c /var/www/run-prod.sh

networks:
    default:
        external:
          name: '${PROXY_NETWORK}'
